nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: [ ]
    allow_headers: [ ]
    allow_methods: [ ]
    expose_headers: [ ]
    max_age: 0
    hosts: [ ]
    #Important since allow_origin contains '*'
    origin_regex: false

  paths:
    '^/':
      allow_origin: [ '*' ]
      allow_headers: [ 'X-Custom-Auth', 'Origin', 'Content-Type', 'Accept' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'PATCH', 'OPTIONS' ]
      max_age: 0
      # This may not be needed ?
      forced_allow_origin_value: '*'




